lean-delivery/ansible-role-sonarqube

README.md, defaults/main.yml, tasks/main.yml, tasks/system/Linux.yml, templates/nginx.sonar.conf.j2, tests/playbook.yml, tests/vars.yml, vars/main.yml
Fix for ansible 2.6.*, plugins update, ability to override optional and excluded plugins
=> Prepare release

README.md, defaults/main.yml, templates/sonar.properties.j2, templates/sonarqube.service.j2
=> Sonarqube server tuning

README.md, defaults/main.yml, tasks/system/Linux.yml, templates/nginx.sonar.conf.j2
* Update git plugin (#26)
* Issue #23 (#27)
* Update main.yml
* Update nginx.sonar.conf.j2
* Update main.yml
* Update main.yml
* Update main.yml
* Update main.yml
* Update main.yml
* Update Linux.yml
* Update nginx.sonar.conf.j2
* update cert path
* fix long line
* Update README.md
* Issues 28 29 (#30)
* update pmd, yaml plugins
* Update README.md
=> Release (#31)

.gitlab-ci.yml, tasks/system/Linux.yml
=> Add loop profiles

tasks/system/Linux.yml, tasks/system/jenkins.yaml
=> issue quick fix

files/example_pipeline.groovy
=> Pipeline example for Jenkins

defaults/main.yml
=> java plugin fix + update

defaults/main.yml
=> branch plugin

.travis.yml, molecule/resources/prepare.yml
=> check lint release

README.md, defaults/main.yml, molecule/cloud-aws-direct/playbook.yml, molecule/cloud-epc-delegated/playbook.yml, molecule/default/playbook.yml, tasks/system/Linux.yml, tasks/system/jenkins.yaml
Add ability to change admin password
- [ *] New feature (non-breaking change which adds functionality)
- [ *] I have performed a self-review of my own code
- [* ] I have made corresponding changes to the documentation
- [ *] My changes generate no new warnings
- [* ] I have added tests that prove my fix is effective or that my feature works
- [* ] New and existing tests pass with my changes
=> add ability to change password

defaults/main.yml
=> plugins update

templates/sonar.properties.j2
=> updatecenter hotfix

.github/workflows/release.yml, .yamllint
=> Add ansible-galaxy role import action

.github/workflows/build.yml
=> refactoring actions for molecule tests

README.md, defaults/main.yml, tasks/system/Linux.yml
=> download hotfix

.github/prepare/action.yml, .github/workflows/build.yml, .gitlab-ci.yml, molecule/cloud-aws-direct/molecule.yml, molecule/cloud-epc-delegated/molecule.yml, molecule/default/molecule.yml, molecule/sonarqube-7.9.6/molecule.yml, molecule/sonarqube-8.0/molecule.yml, molecule/sonarqube-8.1/molecule.yml, molecule/sonarqube-8.2/molecule.yml, molecule/sonarqube-8.3.1/molecule.yml, molecule/sonarqube-8.4.2/molecule.yml, molecule/sonarqube-8.5.1/molecule.yml, molecule/sonarqube-8.6.1/molecule.yml, molecule/sonarqube-8.7.1/molecule.yml
=> add env vars

README.md, meta/main.yml, molecule/cloud-aws-direct/molecule.yml, molecule/default/molecule.yml
=> add centos8, ubuntu16 tests

molecule/cloud-aws-direct/molecule.yml, molecule/cloud-epc-delegated/molecule.yml, molecule/default/molecule.yml, molecule/sonarqube-7.9.6/molecule.yml, molecule/sonarqube-8.0/molecule.yml, molecule/sonarqube-8.1/molecule.yml, molecule/sonarqube-8.2/molecule.yml, molecule/sonarqube-8.3.1/molecule.yml, molecule/sonarqube-8.4.2/molecule.yml, molecule/sonarqube-8.5.1/molecule.yml, molecule/sonarqube-8.6.1/molecule.yml, molecule/sonarqube-8.7.1/molecule.yml, molecule/sonarqube-8.8.0/molecule.yml
=> correct molecule tests

README.md, defaults/main.yml, tasks/system/Linux.yml, templates/sonar.properties.j2
=> branch plugin update and fix

README.md, defaults/main.yml
=> sonar 8.9.5

tasks/system/Linux.yml, templates/sonarqube.service.j2
=> couple of fixes for a successful deployment

.gitmodules, defaults/main.yml
=> text plugin

.gitmodules, defaults/main.yml
=> mutation plugin

handlers/main.yml, tasks/system/Linux.yml
=> fix handlers

defaults/main.yml
=> fix log for 9.6

defaults/main.yml
=> sonar 9.6 preparation

meta/main.yml
=> fix meta file

.github/workflows/build.yml, sonar-project.properties
=> sonarcloud

defaults/main.yml, files/example_pipeline.groovy
=> update pipeline example

sonar-project.properties
=> sonarcloud test

defaults/main.yml, tasks/system/Linux.yml
=> text plugin update

defaults/main.yml
=> sonar 9.7 preparation

defaults/main.yml
=> sonar 9.8 preparation

.gitmodules, defaults/main.yml
=> track dotnet-plugin

defaults/main.yml
=> fix js plugin version

defaults/main.yml
=> fix branch plugin

defaults/main.yml
=> fix plugins

.gitmodules, README.md, defaults/main.yml
=> add aem plugin

defaults/main.yml
=> update branch plugin

defaults/main.yml
=> update iac plugin

.github/workflows/build.yml
=> add timeout

.github/workflows/build.yml, README.md, defaults/main.yml
=> sonar 10.4

.gitmodules, defaults/main.yml, tasks/system/Linux.yml
=> track cayc plugin

defaults/main.yml, tasks/system/Linux.yml
=> switch off typescript plugin

defaults/main.yml
=> fix pmd plugin

defaults/main.yml
=> fix aem plugin

defaults/main.yml
=> fix jdepend plugin

defaults/main.yml
=> findbugs plugin path fix

defaults/main.yml
=> dotnet plugins update

defaults/main.yml
=> dotnet plugin fix

README.md, defaults/main.yml, tasks/system/Linux.yml
=> #4572 and #5447
